[package]
name = "rusty-tokens"
version = "0.1.8"
authors = ["Jannic Hartwecker <jannic.hartwecker@zalando.de>", "Christian Douven <christian.douven@zalando.de>"]
license = "MIT"
description = "An authentication and authorization library for Rust in the Zalando landscape."

[dependencies]
log = "0.3"
rustc-serialize = { version = "*" }

hyper = { version = "0.9", optional = true }
iron = { version = "0.4", optional = true }

[dependencies.http-error-object]
git = "https://github.com/zalando-incubator/http-error-object-rs.git"
tag = "v0.1.4"


[dev-dependencies]
env_logger = "0.3"

[features]
default = ["hyper", "iron"]
